version: "3"
services:
  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - "8085:8085"
  seq: 
    image: datalust/seq
    ports:
      - "5341:5341"
      - "4342:80"
    volumes:
      - rps_seq_data1:/data
    environment:
      - ACCEPT_EULA=Y
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  test:
    build:
      context: .
      dockerfile: XunitTest/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - featurehub

  PatientService:
    image: doncusspelunkus/dls_devops
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - featurehub

  MeasurementService:
    image: measurement-service
    build:
      context: .
      dockerfile: MeasurementService/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - featurehub
      - zipkin
      - seq

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"  # Set your own strong password here
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"  # Expose the SQL Server port
    volumes:
      - ./data:/var/opt/mssql/data
  
  
  streamlit-app:
    build:
      context: .
      dockerfile: PatientFront/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501

  doctor-app:
    build:
      context: .
      dockerfile: DoctorFront/Dockerfile
    ports:
      - "8502:8502"
    environment:
      - STREAMLIT_SERVER_PORT=8501

volumes:
  featurehub-h2-data:
  rps_seq_data1:
