version: "3"
services:
  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - "8085:8085"
  seq: 
    image: datalust/seq
    ports:
      - "5341:5341"
      - "4342:80"
    volumes:
      - rps_seq_data1:/data
    environment:
      - ACCEPT_EULA=Y


  Test:
    image: test
    build:
      context: .
      dockerfile: XunitTest/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - featurehub

  PatientService:
    image: patient-service
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - featurehub

    
volumes:
  featurehub-h2-data:
  rps_seq_data1:
